server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sjkj?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5DialectUTF8
  http:
    encoding:
      charset: utf-8
      enabled: true
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5
  servlet:
    multipart:
      max-file-size: 10M
      max-request-size: 10M

#  mvc:
#    static-path-pattern: /static/*
     #默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  resources:
    staticLocations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

